### ISSUE TITLE
cluster setup command incomplete

### ISSUE THREAD

**Issue by afeld** [philips/2016-OSCON-containers-at-scale-with-Kubernetes#2]
I tried running the command from the [cluster setup](https://github.com/philips/2016-OSCON-containers-at-scale-with-Kubernetes#initial-cluster-setup) section...looks like part of the command got cut off? Would be helpful to let people know where to find the values for the other required flags. Very possible that I missed an earlier step which would have solved this. Thanks!

```
$ kube-aws version
kube-aws version v0.7.0
$ kube-aws init --cluster-name=mycluster \
> --external-dns-name=mycluster.example.com \
>
Error: Missing required flag(s): "--region", "--availability-zone", "--key-name", "--kms-key-arn"
```

**Comment by afeld** [comment]
In case anyone else gets stuck, full example is here:

https://coreos.com/kubernetes/docs/latest/kubernetes-on-aws.html#initialize-an-asset-directory

**Comment by philips** [comment]
I removed this and point to the docs exclusively now.
